config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  root to: "homes#top"
  get "home/about"=>"homes#about"

  resources :users, only: [:index, :show, :edit, :update] do
    member do
    get :follows, :followers
    end
    resource :relationships, only: [:create, :destroy]
  end

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update]  do
    resource :favorites , only: [:create , :destroy]
    resources :book_comments,only:[:create,:destroy]
  end

  get 'searches/search', to: 'searches#search'
  get 'tagsearches/search', to: 'tagsearches#search'

  resources :messages, only: [:create]
  resources :rooms, only: [:create,:show]
  
  resources :groups do
    get "join" => "groups#join"
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  
  belongs_to :user
  validates :title,presence:true
  validates :body,presence:true,length:{maximum:200}
  validates :category,presence:true

  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  #sort-function
  scope :latest, -> {order(created_at: :desc)}
  scope :old, -> {order(created_at: :asc)}
  scope :star_count, -> {order(star: :desc)}

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end   

  #閲覧数
  has_many :view_counts, dependent: :destroy
  
  # 検索機能
  
  def self.search_for(content, method)
    if method == 'perfect'
      Book.where(title: content)
    elsif method == 'forward'
      Book.where('title LIKE ?', content+'%')
    elsif method == 'backward'
      Book.where('title LIKE ?', '%'+content)
    else
      Book.where('title LIKE ?', '%'+content+'%')
    end
  end
  
end

app/models/book_comment.rb
class BookComment < ApplicationRecord

  belongs_to :user
  belongs_to :book
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users
  has_many :users, through: :group_users

  validates :name, presence: true
  validates :introduction, presence: true
  attachment :image, destroy: false
  
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/message.rb
class Message < ApplicationRecord
  validates :message, presence: true
  belongs_to :user
  belongs_to :room
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :profile_image
  
  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  #group用
  has_many :group_users
  has_many :groups, through: :group_users 

   #DM
   has_many :messages, dependent: :destroy
   has_many :entries, dependent: :destroy
   #閲覧数
   has_many :view_counts, dependent: :destroy
   
  #relationshipModel assosiation
  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy # ① フォローしている人取得(Userのfollowerから見た関係)
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy # ② フォローされている人取得(Userのfolowedから見た関係)
  has_many :following_user, through: :follower, source: :followed # 自分がフォローしている人
  has_many :follower_user, through: :followed, source: :follower # 自分をフォローしている人

  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction,length: { maximum: 50 }

  # ユーザーをフォローする
  def follow(user_id)
    follower.create(followed_id: user_id)
  end

  # ユーザーのフォローを外す
  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end

  # フォローしていればtrueを返す
  def following?(user)
    following_user.include?(user)
  end
 
  def get_profile_image
    (profile_image.attached?) ? profile_image : 'no_image.jpg'
  end

  # Seach-function
  def self.search_for(content, method)
    if method == 'perfect'
      User.where(name: content)
    elsif method == 'forward'
      User.where('name LIKE ?', content + '%')
    elsif method == 'backward'
      User.where('name LIKE ?', '%' + content)
    else
      User.where('name LIKE ?', '%' + content + '%')
    end
  end


end

app/models/view_count.rb
class ViewCount < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_correct_user, only: [:update]


  def show
    @user = User.find(params[:id])
   # @user = User.find(current_user.id)
    @books = @user.books
    @book = Book.new
    @btn = "Create Book"
    @following_users = @user.following_user
    @follower_users = @user.follower_user

    # DM機能
    @currentUserEntry=Entry.where(user_id: current_user.id)
    @userEntry=Entry.where(user_id: @user.id)
    if @user.id == current_user.id
    else
      @currentUserEntry.each do |cu|
        @userEntry.each do |u|
          if cu.room_id == u.room_id then
            @isRoom = true
            @roomId = cu.room_id
          end
        end
      end
      if @isRoom
      else
        @room = Room.new
        @entry = Entry.new
      end
    end
  end
  

  def index
    @users = User.all
    @book = Book.new
    @btn = "Create Book"
   #  @users = User.page(params[:page]).per(3).reverse_order

  end  

  def edit
    @user = User.find(params[:id])
    
    user_id = params[:id].to_i
    unless user_id == current_user.id
     redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to user_path(@user), notice: "You have updated user successfully."
    else
      
      render :edit
    end
  end

  def follows
    user = User.find(params[:id])

    
    # @following_users = user.following_user.includes(:followed, :follower)
    @following_users = user.following_user
    # @follower_users = user.follower_user.includes(:followed, :follower)
    @follower_users = user.follower_user

  end

  def followers
    user = User.find(params[:id])
    @following_users = user.following_user
    @follower_users = user.follower_user
  end


  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end

 
end  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favolites_helper.rb
module FavolitesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/rooms　_helper.rb
module Rooms　Helper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= image_tag user.get_profile_image, size: '50x50' %></td>
        <td><%= user.name %></td>
        <td>
            <h6>フォロー数:<%= user.follower.count %></h6>
        </td>
        <td>  
            <h6>フォロワー数:<%= user.followed.count %></h6>
        </td>
        <td><%= link_to 'Show', user %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<table class='table'>
  <tr><%= image_tag user.get_profile_image, size:'100x100' %></tr>
  <tr>
	  <th>name</th>
	  <td><%= user.name %></td>
  </tr>
  <tr>
	  <th>introduction</th>
	  <td><%= user.introduction %></td>
  </tr>
  <tr>
    <th>Follows</th>
    <td>
      <%= link_to follows_user_path(user) do %>
        <h6><%= user.follower.count %></h6>
      <% end %> 
    </td>
  </tr>
  <tr>  
    <th>Followers</th>
    <td>  
      <%= link_to followers_user_path(user) do %>
        <h6><%= user.followed.count %></h6>
      <% end %>
    </td>
  </tr> 
  <tr>
    <td>
      <div class='row mb-4'>
        <% if current_user != user %>
          <% if current_user.following?(user) %>
          <%= link_to 'フォロー外す', user_relationships_path(user.id), method: :delete, class: "btn-sm btn-danger" %>
          <% else %>
          <%= link_to 'フォローする', user_relationships_path(user.id), method: :post, class:"btn-sm btn-success" %>
          <% end %>
        <% end %>
      </div>
    </td>
    <td>
      <% unless user.id == current_user.id %>
      <% if (current_user.following? user) && (user.following? current_user)  %>
        <% if isRoom == true %>
          <p class="user-show-room"><a href="/rooms/<%= roomId %>" ">チャットへ</a>
        <% else %>
          <%= form_for room do |f| %>
            <%= fields_for entry do |e| %>
              <%= e.hidden_field :user_id, value: user.id %>
            <% end %>
            <%= f.submit "チャットを始める"%>
          <% end %>
        <% end %>
      <% end %>
    <% end %>
    </td>
  </tr>  
</table>

<div class='row'>
  <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block" do %>
    <i class="fas fa-user-cog"></i>
  <% end %>
</div>

app/views/users/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
    
    <%= form_with model:@user, local:true do |f| %>
      <%= render 'layouts/errors', obj: @user %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
     <div class="form-group">
        <%= f.label :image %>
        <%= f.file_field :profile_image, class: "form-control-file user_image", accept: 'image/*' %>
      </div>
      <div class="form-group">
        <%= f.label :introduction %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-secondary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/followers.html.erb
<h1>Follower Users</h1>

<table class='table'>
  <thead>
    <tr>
      <th>Image</th>
      <th>name</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @follower_users.each do |user| %>
      <tr>
        <td>
          <%= link_to user_path(user) do %>
            <%= image_tag user.get_profile_image, size:'50x50' %>
          <% end %>
        </td>
        <td><%= user.name %></td>
        <td>
          <%= link_to follows_user_path(user) do %>
            <h6>フォロー<%= user.follower.count %></h6>
          <% end %>
        </td>
        <td>  
          <%= link_to followers_user_path(user) do %>
            <h6>フォロワー<%= user.followed.count %></h6>
          <% end %>
        </td>
      </tr>
    <% end %>
    </tbody>

</table>   

app/views/users/follows.html.erb
<h1>Follow Users</h1>

    <table class='table'>
      <thead>
        <tr>
          <th>Image</th>
          <th>name</th>
          <th></th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @following_users.each do |user| %>
          <tr>
            <td>
              <%= link_to user_path(user) do %>
                <%= image_tag user.get_profile_image, size:'50x50' %>
              <% end %>
            </td>
            <td><%= user.name %></td>
            <td>
              <%= link_to follows_user_path(user) do %>
                <h6>フォロー<%= user.follower.count %></h6>
              <% end %>
            </td>
            <td>  
              <%= link_to followers_user_path(user) do %>
                <h6>フォロワー<%= user.followed.count %></h6>
              <% end %>
            </td>
          </tr>
        <% end %>
        </tbody>
    </table> 

app/views/users/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
        <h2>User info</h2>
        <%= render 'users/info', user: current_user %>
    
        <h2 class="mt-3">New book</h2>
        <%= render partial: 'books/form', locals: { book: @book, btn:@btn, isEdit: false } %>
    </div>
    <div class='col-md-8 offset-md-1'>
        <h2>Users</h2>
        <div><%=link_to "グループを作成する",new_group_path %> | <%=link_to "グループ一覧",groups_path %></div>
        
        <%= render 'users/index',users: @users %>
    </div>    
  </div>   
</div>      

app/views/users/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>

      <%= render 'users/info', user: @user,isRoom:@isRoom,roomId:@roomId,room:@room,entry:@entry %>

      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book, btn:@btn, isEdit: false %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'books/index',books: @books %>
    </div>
  </div>
</div>