config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  root to: "homes#top"
  get "home/about"=>"homes#about"

  resources :users, only: [:index, :show, :edit, :update] do
    member do
    get :follows, :followers
    end
    resource :relationships, only: [:create, :destroy]
  end

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update]  do
    resource :favorites , only: [:create , :destroy]
    resources :book_comments,only:[:create,:destroy]
  end

  get 'searches/search', to: 'searches#search'
  get 'tagsearches/search', to: 'tagsearches#search'

  resources :messages, only: [:create]
  resources :rooms, only: [:create,:show]
  
  resources :groups do
    get "join" => "groups#join"
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  
  belongs_to :user
  validates :title,presence:true
  validates :body,presence:true,length:{maximum:200}
  validates :category,presence:true

  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  #sort-function
  scope :latest, -> {order(created_at: :desc)}
  scope :old, -> {order(created_at: :asc)}
  scope :star_count, -> {order(star: :desc)}

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end   

  #閲覧数
  has_many :view_counts, dependent: :destroy
  
  # 検索機能
  
  def self.search_for(content, method)
    if method == 'perfect'
      Book.where(title: content)
    elsif method == 'forward'
      Book.where('title LIKE ?', content+'%')
    elsif method == 'backward'
      Book.where('title LIKE ?', '%'+content)
    else
      Book.where('title LIKE ?', '%'+content+'%')
    end
  end
  
end

app/models/book_comment.rb
class BookComment < ApplicationRecord

  belongs_to :user
  belongs_to :book
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users
  has_many :users, through: :group_users

  validates :name, presence: true
  validates :introduction, presence: true
  attachment :image, destroy: false
  
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/message.rb
class Message < ApplicationRecord
  validates :message, presence: true
  belongs_to :user
  belongs_to :room
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :profile_image
  
  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  #group用
  has_many :group_users
  has_many :groups, through: :group_users 

   #DM
   has_many :messages, dependent: :destroy
   has_many :entries, dependent: :destroy
   #閲覧数
   has_many :view_counts, dependent: :destroy
   
  #relationshipModel assosiation
  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy # ① フォローしている人取得(Userのfollowerから見た関係)
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy # ② フォローされている人取得(Userのfolowedから見た関係)
  has_many :following_user, through: :follower, source: :followed # 自分がフォローしている人
  has_many :follower_user, through: :followed, source: :follower # 自分をフォローしている人

  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction,length: { maximum: 50 }

  # ユーザーをフォローする
  def follow(user_id)
    follower.create(followed_id: user_id)
  end

  # ユーザーのフォローを外す
  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end

  # フォローしていればtrueを返す
  def following?(user)
    following_user.include?(user)
  end
 
  def get_profile_image
    (profile_image.attached?) ? profile_image : 'no_image.jpg'
  end

  # Seach-function
  def self.search_for(content, method)
    if method == 'perfect'
      User.where(name: content)
    elsif method == 'forward'
      User.where('name LIKE ?', content + '%')
    elsif method == 'backward'
      User.where('name LIKE ?', '%' + content)
    else
      User.where('name LIKE ?', '%' + content + '%')
    end
  end


end

app/models/view_count.rb
class ViewCount < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def show
    @book = Book.find(params[:id])
    unless ViewCount.find_by(user_id: current_user.id, book_id: @book.id)
      current_user.view_counts.create(book_id: @book.id)
    end
    @newBook = Book.new
    @user = @book.user
    @btn = "Create Book"
    @book_comment = BookComment.new
    @following_users = @user.following_user
    @follower_users = @user.follower_user
    
    # DM機能
    @currentUserEntry=Entry.where(user_id: current_user.id)
    @userEntry=Entry.where(user_id: @user.id)
    if @user.id == current_user.id
    else
      @currentUserEntry.each do |cu|
        @userEntry.each do |u|
          if cu.room_id == u.room_id then
            @isRoom = true
            @roomId = cu.room_id
          end
        end
      end
      if @isRoom
      else
        @room = Room.new
        @entry = Entry.new
      end
    end
  end

  def index
    
    to  = Time.current.at_end_of_day
    from  = (to - 6.day).at_beginning_of_day
    @books = Book.includes(:favorites).sort_by {|x| x.favorites.where(created_at: from...to).size}.reverse
    
    if params[:latest]
        @books = Book.latest
    elsif params[:old]
        @books = Book.old
    elsif params[:star_count]
        @books = Book.star_count
    else
        @books = Book.all
    end



    @book = Book.new
    #@books = Book.all
    @btn = "Create Book"
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book), notice: "You have created book successfully."
    else
      @books = Book.all
      render :index
    end
  end

  def edit
    @book = Book.find(params[:id])
    @btn = "Update Book"
    if @book.user == current_user
      render :edit
    else
       redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book.id), notice: "You have updated book successfully."
    else
      @btn = "Update Book"
      render "edit"
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body, :image, :star,:category)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favolites_helper.rb
module FavolitesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/rooms　_helper.rb
module Rooms　Helper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_form.html.erb
<%= form_with model: book do |f| %>
  <div class="form-group">
    <label for="book_title">Title</label>
    <%= f.text_field :title, class: 'form-control book_title' %>
  </div>
  <div class="form-group">
    <label for="book_body">Opinion</label>
    <%= f.text_area :body, class: 'form-control book_body' %>
  </div>
  <div class="form-group">
    <label>Category</label>
    <%= f.text_field :category,class: 'form-control book_category' %>
  </div>
  <div id="stars">
    <label>Rate</label>
  </div>
    
  <div class="form-group">
    <%= f.submit btn , class: 'btn btn-success' %>
  </div>
<% end %>
<script>
  let elem = document.querySelector('#stars');
  let opt = {
    starOn: "<%= asset_path('star-on.png') %>",
    starOff: "<%= asset_path('star-off.png') %>",
    starHalf: "<%= asset_path('star-half.png') %>",
    scoreName: 'book[star]',
    score: "<%= isEdit ? book.star : 0 %>"
  };
  window.raty(elem, opt);
</script>

app/views/books/_index.html.erb
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% books.each do |book| %>
    <tr>
      <td><%= link_to user_path(book.user) do %>
        <%= image_tag book.user.get_profile_image, size:'50x50' %>
        <% end %>
      </td>
      <td><%= link_to book.title, book_path(book.id) %></td>
      <td><%= book.body %></td>
    
      <!--いいね機能ajax-partial-->
      <td id="favorite_buttons_<%= book.id %>">
          <%= render "favorites/favorites", book: book %>
      </td>
      <td>
        <% if book.category.present? %>
          <%= link_to book.category, tagsearches_search_path(content: book.category) %></td>
        <% end %>
      </td>
      <td>
        <div id="index-stars-<%= book.id %>"> </div>
      </td>

      <td>  
          <%= link_to "#{book.book_comments.count} コメント", book_path(book.id) %>
      </td>
      <td><p class="view-count">閲覧数: <%= @book.view_counts.count %></p></td>
    </tr>
    <script>
      window.raty(document.querySelector('#index-stars-<%= book.id %>'), {
        starOn: "<%= asset_path('star-on.png') %>",
        starOff: "<%= asset_path('star-off.png') %>",
        starHalf: "<%= asset_path('star-half.png') %>",
        scoreName: 'book[star]',
        score: "<%= book.star %>",
        readOnly: true
      });
    </script>
    <% end %>
  </tbody>
</table>

app/views/books/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
		  <%= render partial: 'layouts/errors', locals: { obj:@book } %>
  		<h1>Editing Book</h1>
  		<%= render partial: 'books/form', locals: { book: @book, btn: @btn, isEdit: true } %>
			
  		<%= link_to 'Show', @book %> |
  		<%= link_to 'Back', books_path, class: "back" %>
  </div>
</div>

app/views/books/index.html.erb
<div class='container px-5 px-sm-0'>
  <%= render 'layouts/errors', obj:@book %>
  
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render partial: 'books/form', locals: { book: @book, btn:@btn, isEdit: false } %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <p>
        <%= link_to '新しい順', books_path(latest: "true") %> |
        <%= link_to '古い順', books_path(old: "true") %> |
        <%= link_to '評価の高い順', books_path(star_count: "true") %>
      </p>
      <%= render 'books/index', books: @books%>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class='container'>
  <%= render 'layouts/errors', obj:@book %>
  
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user:@user,isRoom:@isRoom,roomId:@roomId,room:@room,entry:@entry %>
      <h2 class="mt-3">New book</h2>
      <%= render partial: 'books/form', locals: { book: @newBook, btn:@btn, isEdit: false } %>
    </div>
    <div class='col-md-8 offset-md-1'>
  		<h2>Book detail</h2>
  		<table class='table'>
        
  		  <tr>
          <td>
            <%= link_to user_path(@user) do %>
            <%= image_tag @user.get_profile_image, size:"100x100" %><br>
            <%= @user.name %>
            <% end %>
          </td>
          <td><%= link_to @book.title, @book %></td>
          <td><%= @book.body %></td>
          <td>
            <% if @book.category.present? %>
            <%= link_to @book.category, tagsearches_search_path(content: @book.category) %>
            <% end %>
          </td>
          
          <td id="favorite_buttons_<%= @book.id %>">
            <%= render "favorites/favorites", book: @book %>
          </td>
          <td>
            <div id="show-stars"></div>
          </td>
          <td>
            <div>コメント件数：<span id="comment_count"><%= @book.book_comments.count %></span></div>
          </td> 

          <% if @book.user == current_user %>
            <td><%= link_to 'Edit', edit_book_path(@book), method: :get, class: "btn btn-sm btn-success" %></td>
            <td><%= link_to 'Destroy', @book, method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger"%></td>
          <% end %>

        </tr>  
      </table>
        
      <div id="book-comments">
        <%= render "book_comments/commentslist", book: @book %>
      </div>
       
      <div id="comment-form">
        <%= render "book_comments/form", book: @book,book_comment:@book_comment %>
      </div>
    </div>
  </div>
</div>

<script>
  let showRateElement = document.querySelector('#show-stars');
  let showOpt = {
    starOn: "<%= asset_path('star-on.png') %>",
    starOff: "<%= asset_path('star-off.png') %>",
    starHalf: "<%= asset_path('star-half.png') %>",
    scoreName: 'book[star]',
    score: "<%= @book.star %>",
    readOnly: true
  };
  window.raty(showRateElement, showOpt);
</script>